### PR TITLE
add helm chart

### PR DESCRIPTION
**Pull request by xavier-hou**
Signed-off-by: hxcGit <houxc_mail@163.com>

### CODE REVIEW

**Comment by xavier-hou** [comment]
Related issue： https://github.com/openyurtio/raven/issues/73

**Comment by xavier-hou** [comment]
@njucjc @DrmagicE @rambohe-ch  PTAL

**Comment by xavier-hou** [comment]
According to https://github.com/openyurtio/openyurt/pull/905, we also need to create a secret key `OPENYURT_API_DEPLOY` for `raven-controller-manager`.  And btw, what is the appropriate chart version and application version for `raven-controller-manager`?

**Comment by njucjc** [comment]
> According to [openyurtio/openyurt#905](https://github.com/openyurtio/openyurt/pull/905), we also need to create a secret key `OPENYURT_API_DEPLOY` for `raven-controller-manager`. And btw, what is the appropriate chart version and application version for `raven-controller-manager`?

application version：v0.2.0

**Pull request merged**
